/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accessTokensListAccessTokens } from "../../funcs/accessTokensListAccessTokens.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAccessTokensRequest$inboundSchema,
};

export const tool$accessTokensListAccessTokens: ToolDefinition<typeof args> = {
  name: "access-tokens-list-access-tokens",
  description: `List access tokens.`,
  scopes: ["read", "read", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accessTokensListAccessTokens(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
