/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basinsCreateBasin } from "../../funcs/basinsCreateBasin.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateBasinRequest$inboundSchema,
};

export const tool$basinsCreateBasin: ToolDefinition<typeof args> = {
  name: "basins-create-basin",
  description: `Create a basin.`,
  scopes: ["write", "write", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basinsCreateBasin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
