/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basinsCreateOrReconfigureBasin } from "../../funcs/basinsCreateOrReconfigureBasin.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateOrReconfigureBasinRequest$inboundSchema,
};

export const tool$basinsCreateOrReconfigureBasin: ToolDefinition<typeof args> =
  {
    name: "basins-create-or-reconfigure-basin",
    description: `Create or reconfigure a basin.`,
    scopes: ["write"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await basinsCreateOrReconfigureBasin(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
