/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basinsGetBasinConfig } from "../../funcs/basinsGetBasinConfig.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBasinConfigRequest$inboundSchema,
};

export const tool$basinsGetBasinConfig: ToolDefinition<typeof args> = {
  name: "basins-get-basin-config",
  description: `Get basin config.`,
  scopes: ["read", "read", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basinsGetBasinConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
