/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsAccountMetrics } from "../../funcs/metricsAccountMetrics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AccountMetricsRequest$inboundSchema,
};

export const tool$metricsAccountMetrics: ToolDefinition<typeof args> = {
  name: "metrics-account-metrics",
  description: `Account-level metrics.`,
  scopes: ["read", "read", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsAccountMetrics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
