/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recordsCheckTail } from "../../funcs/recordsCheckTail.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CheckTailRequest$inboundSchema,
};

export const tool$recordsCheckTail: ToolDefinition<typeof args> = {
  name: "records-check-tail",
  description: `Check the tail.

Check the tail of a stream.`,
  scopes: ["read", "read", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await recordsCheckTail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
