/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamsCreateOrReconfigureStream } from "../../funcs/streamsCreateOrReconfigureStream.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateOrReconfigureStreamRequest$inboundSchema,
};

export const tool$streamsCreateOrReconfigureStream: ToolDefinition<
  typeof args
> = {
  name: "streams-create-or-reconfigure-stream",
  description: `Create or reconfigure a stream.`,
  scopes: ["write", "write", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamsCreateOrReconfigureStream(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
