/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamCheckTail } from "../../funcs/streamCheckTail.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CheckTailRequest$inboundSchema,
};

export const tool$streamCheckTail: ToolDefinition<typeof args> = {
  name: "stream-check-tail",
  description: `Check the tail.

Check the sequence number that will be assigned to the next record on a stream.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamCheckTail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
