/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamsCreateStream } from "../../funcs/streamsCreateStream.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateStreamRequest$inboundSchema,
};

export const tool$streamsCreateStream: ToolDefinition<typeof args> = {
  name: "streams-create-stream",
  description: `Create a stream.`,
  scopes: ["write", "write", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamsCreateStream(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
