/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamsListStreams } from "../../funcs/streamsListStreams.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListStreamsRequest$inboundSchema,
};

export const tool$streamsListStreams: ToolDefinition<typeof args> = {
  name: "streams-list-streams",
  description: `List streams.`,
  scopes: ["read", "read", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamsListStreams(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
