/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { S2Core } from "../core.js";
import { encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { CheckTailServerList } from "../models/operations/checktail.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

/**
 * Check the tail.
 *
 * @remarks
 * Check the sequence number that will be assigned to the next record on a stream.
 */
export async function streamCheckTail(
  client: S2Core,
  request: operations.CheckTailRequest,
  options?: RequestOptions,
): Promise<
  Result<
    components.CheckTailResponse,
    | errors.ErrorResponse
    | errors.RetryableError
    | errors.RetryableError
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const parsed = safeParse(
    request,
    (value) => operations.CheckTailRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return parsed;
  }
  const payload = parsed.value;
  const body = null;

  const baseURL = options?.serverURL
    || pathToFunc(CheckTailServerList[0], { charEncoding: "percent" })({
      basin: "my-favorite-basin",
    });

  const pathParams = {
    stream: encodeSimple("stream", payload.stream, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/streams/{stream}/records/tail")(pathParams);

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.bearerAuth);
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    operationID: "check_tail",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: baseURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "401", "404", "499", "4XX", "500", "503", "504", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    components.CheckTailResponse,
    | errors.ErrorResponse
    | errors.RetryableError
    | errors.RetryableError
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, components.CheckTailResponse$inboundSchema),
    M.jsonErr([400, 401, 404], errors.ErrorResponse$inboundSchema),
    M.jsonErr(499, errors.RetryableError$inboundSchema),
    M.jsonErr([500, 503, 504], errors.RetryableError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return result;
  }

  return result;
}
