/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountCreateBasin } from "../funcs/accountCreateBasin.js";
import { accountDeleteBasin } from "../funcs/accountDeleteBasin.js";
import { accountGetBasinConfig } from "../funcs/accountGetBasinConfig.js";
import { accountListBasins } from "../funcs/accountListBasins.js";
import { accountReconfigureBasin } from "../funcs/accountReconfigureBasin.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Account extends ClientSDK {
  async listBasins(
    request: operations.ListBasinsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListBasinsResponse, { cursor: string }>> {
    return unwrapResultIterator(accountListBasins(
      this,
      request,
      options,
    ));
  }

  async getBasinConfig(
    request: operations.GetBasinConfigRequest,
    options?: RequestOptions,
  ): Promise<components.BasinConfig> {
    return unwrapAsync(accountGetBasinConfig(
      this,
      request,
      options,
    ));
  }

  async createBasin(
    request: operations.CreateBasinRequest,
    options?: RequestOptions,
  ): Promise<components.BasinInfo> {
    return unwrapAsync(accountCreateBasin(
      this,
      request,
      options,
    ));
  }

  async deleteBasin(
    request: operations.DeleteBasinRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(accountDeleteBasin(
      this,
      request,
      options,
    ));
  }

  async reconfigureBasin(
    request: operations.ReconfigureBasinRequest,
    options?: RequestOptions,
  ): Promise<components.ReconfigureBasinResponse> {
    return unwrapAsync(accountReconfigureBasin(
      this,
      request,
      options,
    ));
  }
}
