/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basinCreateStream } from "../funcs/basinCreateStream.js";
import { basinDeleteStream } from "../funcs/basinDeleteStream.js";
import { basinGetStreamConfig } from "../funcs/basinGetStreamConfig.js";
import { basinListStreams } from "../funcs/basinListStreams.js";
import { basinReconfigureStream } from "../funcs/basinReconfigureStream.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Basin extends ClientSDK {
  /**
   * List Streams.
   */
  async listStreams(
    request: operations.ListStreamsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListStreamsResponse, { cursor: string }>> {
    return unwrapResultIterator(basinListStreams(
      this,
      request,
      options,
    ));
  }

  /**
   * Get stream configuration.
   */
  async getStreamConfig(
    request: operations.GetStreamConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStreamConfigResponse> {
    return unwrapAsync(basinGetStreamConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a stream.
   */
  async createStream(
    request: operations.CreateStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateStreamResponse> {
    return unwrapAsync(basinCreateStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a stream.
   */
  async deleteStream(
    request: operations.DeleteStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteStreamResponse> {
    return unwrapAsync(basinDeleteStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Update stream configuration.
   */
  async reconfigureStream(
    request: operations.ReconfigureStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.ReconfigureStreamResponse> {
    return unwrapAsync(basinReconfigureStream(
      this,
      request,
      options,
    ));
  }
}
