/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Account } from "./account.js";
import { Basin } from "./basin.js";
import { Stream } from "./stream.js";

export class S2 extends ClientSDK {
  private _account?: Account;
  get account(): Account {
    return (this._account ??= new Account(this._options));
  }

  private _basin?: Basin;
  get basin(): Basin {
    return (this._basin ??= new Basin(this._options));
  }

  private _stream?: Stream;
  get stream(): Stream {
    return (this._stream ??= new Stream(this._options));
  }
}
