workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    S2 API:
        inputs:
            - location: https://raw.githubusercontent.com/s2-streamstore/s2-protos/refs/heads/main/s2/v1/openapi.json
        overlays:
            - location: overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/stream-store/s2/s-2-api
targets:
    streamstore:
        target: typescript
        source: S2 API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/stream-store/s2/s-2-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
