/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const AppendServerList = [
  /**
   * Endpoint for the basin
   */
  "https://{basin}.b.aws.s2.dev/v1",
] as const;

export type AppendRequest = {
  /**
   * Stream name.
   */
  stream: string;
  /**
   * Define treatment of blob fields when exchanging records as JSON.
   *
   * @remarks
   * The default is `raw`.
   */
  s2Format?: components.S2Format | undefined;
  /**
   * Basin name for basin-specific endpoints
   */
  s2Basin: string;
  appendInput: components.AppendInput;
};

/** @internal */
export const AppendRequest$inboundSchema: z.ZodType<
  AppendRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  stream: z.string(),
  "s2-format": components.S2Format$inboundSchema.optional(),
  "s2-basin": z.string(),
  AppendInput: components.AppendInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "s2-format": "s2Format",
    "s2-basin": "s2Basin",
    "AppendInput": "appendInput",
  });
});

/** @internal */
export type AppendRequest$Outbound = {
  stream: string;
  "s2-format"?: string | undefined;
  "s2-basin": string;
  AppendInput: components.AppendInput$Outbound;
};

/** @internal */
export const AppendRequest$outboundSchema: z.ZodType<
  AppendRequest$Outbound,
  z.ZodTypeDef,
  AppendRequest
> = z.object({
  stream: z.string(),
  s2Format: components.S2Format$outboundSchema.optional(),
  s2Basin: z.string(),
  appendInput: components.AppendInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    s2Format: "s2-format",
    s2Basin: "s2-basin",
    appendInput: "AppendInput",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppendRequest$ {
  /** @deprecated use `AppendRequest$inboundSchema` instead. */
  export const inboundSchema = AppendRequest$inboundSchema;
  /** @deprecated use `AppendRequest$outboundSchema` instead. */
  export const outboundSchema = AppendRequest$outboundSchema;
  /** @deprecated use `AppendRequest$Outbound` instead. */
  export type Outbound = AppendRequest$Outbound;
}

export function appendRequestToJSON(appendRequest: AppendRequest): string {
  return JSON.stringify(AppendRequest$outboundSchema.parse(appendRequest));
}

export function appendRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppendRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppendRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppendRequest' from JSON`,
  );
}
