/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BasinMetricsRequest = {
  /**
   * Metric set to return.
   */
  set: components.BasinMetricSet;
  /**
   * Start timestamp as Unix epoch seconds, if applicable for the metric set.
   */
  start?: number | undefined;
  /**
   * End timestamp as Unix epoch seconds, if applicable for the metric set.
   */
  end?: number | undefined;
  /**
   * Interval to aggregate over for timeseries metric sets.
   */
  interval?: components.TimeseriesInterval | undefined;
  /**
   * Basin name.
   */
  basin: string;
};

/** @internal */
export const BasinMetricsRequest$inboundSchema: z.ZodType<
  BasinMetricsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  set: components.BasinMetricSet$inboundSchema,
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  interval: components.TimeseriesInterval$inboundSchema.optional(),
  basin: z.string(),
});

/** @internal */
export type BasinMetricsRequest$Outbound = {
  set: string;
  start?: number | undefined;
  end?: number | undefined;
  interval?: string | undefined;
  basin: string;
};

/** @internal */
export const BasinMetricsRequest$outboundSchema: z.ZodType<
  BasinMetricsRequest$Outbound,
  z.ZodTypeDef,
  BasinMetricsRequest
> = z.object({
  set: components.BasinMetricSet$outboundSchema,
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  interval: components.TimeseriesInterval$outboundSchema.optional(),
  basin: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BasinMetricsRequest$ {
  /** @deprecated use `BasinMetricsRequest$inboundSchema` instead. */
  export const inboundSchema = BasinMetricsRequest$inboundSchema;
  /** @deprecated use `BasinMetricsRequest$outboundSchema` instead. */
  export const outboundSchema = BasinMetricsRequest$outboundSchema;
  /** @deprecated use `BasinMetricsRequest$Outbound` instead. */
  export type Outbound = BasinMetricsRequest$Outbound;
}

export function basinMetricsRequestToJSON(
  basinMetricsRequest: BasinMetricsRequest,
): string {
  return JSON.stringify(
    BasinMetricsRequest$outboundSchema.parse(basinMetricsRequest),
  );
}

export function basinMetricsRequestFromJSON(
  jsonString: string,
): SafeParseResult<BasinMetricsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BasinMetricsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BasinMetricsRequest' from JSON`,
  );
}
