/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const CreateStreamServerList = [
  /**
   * Endpoint for the basin
   */
  "https://{basin}.b.aws.s2.dev/v1",
] as const;
