/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateBasinRequest = {
  /**
   * Name of the basin.
   */
  basin: string;
  s2RequestToken?: string | undefined;
  createBasinRequest: components.CreateBasinRequest;
};

/** @internal */
export const CreateBasinRequest$inboundSchema: z.ZodType<
  CreateBasinRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  basin: z.string(),
  "s2-request-token": z.string().optional(),
  CreateBasinRequest: components.CreateBasinRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "s2-request-token": "s2RequestToken",
    "CreateBasinRequest": "createBasinRequest",
  });
});

/** @internal */
export type CreateBasinRequest$Outbound = {
  basin: string;
  "s2-request-token"?: string | undefined;
  CreateBasinRequest: components.CreateBasinRequest$Outbound;
};

/** @internal */
export const CreateBasinRequest$outboundSchema: z.ZodType<
  CreateBasinRequest$Outbound,
  z.ZodTypeDef,
  CreateBasinRequest
> = z.object({
  basin: z.string(),
  s2RequestToken: z.string().optional(),
  createBasinRequest: components.CreateBasinRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    s2RequestToken: "s2-request-token",
    createBasinRequest: "CreateBasinRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBasinRequest$ {
  /** @deprecated use `CreateBasinRequest$inboundSchema` instead. */
  export const inboundSchema = CreateBasinRequest$inboundSchema;
  /** @deprecated use `CreateBasinRequest$outboundSchema` instead. */
  export const outboundSchema = CreateBasinRequest$outboundSchema;
  /** @deprecated use `CreateBasinRequest$Outbound` instead. */
  export type Outbound = CreateBasinRequest$Outbound;
}

export function createBasinRequestToJSON(
  createBasinRequest: CreateBasinRequest,
): string {
  return JSON.stringify(
    CreateBasinRequest$outboundSchema.parse(createBasinRequest),
  );
}

export function createBasinRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateBasinRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBasinRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBasinRequest' from JSON`,
  );
}
