/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateStreamServerList = [
  /**
   * Endpoint for the basin
   */
  "https://{basin}.b.aws.s2.dev/v1alpha",
] as const;

export type CreateStreamRequest = {
  /**
   * Name of the stream.
   */
  stream: string;
  s2RequestToken?: string | undefined;
  createStreamRequest: components.CreateStreamRequest;
};

export type CreateStreamResponse = {
  httpMeta: components.HTTPMetadata;
  streamInfo?: components.StreamInfo | undefined;
};

/** @internal */
export const CreateStreamRequest$inboundSchema: z.ZodType<
  CreateStreamRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  stream: z.string(),
  "s2-request-token": z.string().optional(),
  CreateStreamRequest: components.CreateStreamRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "s2-request-token": "s2RequestToken",
    "CreateStreamRequest": "createStreamRequest",
  });
});

/** @internal */
export type CreateStreamRequest$Outbound = {
  stream: string;
  "s2-request-token"?: string | undefined;
  CreateStreamRequest: components.CreateStreamRequest$Outbound;
};

/** @internal */
export const CreateStreamRequest$outboundSchema: z.ZodType<
  CreateStreamRequest$Outbound,
  z.ZodTypeDef,
  CreateStreamRequest
> = z.object({
  stream: z.string(),
  s2RequestToken: z.string().optional(),
  createStreamRequest: components.CreateStreamRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    s2RequestToken: "s2-request-token",
    createStreamRequest: "CreateStreamRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateStreamRequest$ {
  /** @deprecated use `CreateStreamRequest$inboundSchema` instead. */
  export const inboundSchema = CreateStreamRequest$inboundSchema;
  /** @deprecated use `CreateStreamRequest$outboundSchema` instead. */
  export const outboundSchema = CreateStreamRequest$outboundSchema;
  /** @deprecated use `CreateStreamRequest$Outbound` instead. */
  export type Outbound = CreateStreamRequest$Outbound;
}

export function createStreamRequestToJSON(
  createStreamRequest: CreateStreamRequest,
): string {
  return JSON.stringify(
    CreateStreamRequest$outboundSchema.parse(createStreamRequest),
  );
}

export function createStreamRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateStreamRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateStreamRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateStreamRequest' from JSON`,
  );
}

/** @internal */
export const CreateStreamResponse$inboundSchema: z.ZodType<
  CreateStreamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  StreamInfo: components.StreamInfo$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "StreamInfo": "streamInfo",
  });
});

/** @internal */
export type CreateStreamResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  StreamInfo?: components.StreamInfo$Outbound | undefined;
};

/** @internal */
export const CreateStreamResponse$outboundSchema: z.ZodType<
  CreateStreamResponse$Outbound,
  z.ZodTypeDef,
  CreateStreamResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  streamInfo: components.StreamInfo$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    streamInfo: "StreamInfo",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateStreamResponse$ {
  /** @deprecated use `CreateStreamResponse$inboundSchema` instead. */
  export const inboundSchema = CreateStreamResponse$inboundSchema;
  /** @deprecated use `CreateStreamResponse$outboundSchema` instead. */
  export const outboundSchema = CreateStreamResponse$outboundSchema;
  /** @deprecated use `CreateStreamResponse$Outbound` instead. */
  export type Outbound = CreateStreamResponse$Outbound;
}

export function createStreamResponseToJSON(
  createStreamResponse: CreateStreamResponse,
): string {
  return JSON.stringify(
    CreateStreamResponse$outboundSchema.parse(createStreamResponse),
  );
}

export function createStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateStreamResponse' from JSON`,
  );
}
