/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteStreamServerList = [
  /**
   * Endpoint for the basin
   */
  "https://{basin}.b.aws.s2.dev/v1",
] as const;

export type DeleteStreamRequest = {
  /**
   * Stream name, which must be unique within the basin.
   *
   * @remarks
   * It can be an arbitrary string up to 512 characters.
   */
  stream: string;
};

/** @internal */
export const DeleteStreamRequest$inboundSchema: z.ZodType<
  DeleteStreamRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  stream: z.string(),
});

/** @internal */
export type DeleteStreamRequest$Outbound = {
  stream: string;
};

/** @internal */
export const DeleteStreamRequest$outboundSchema: z.ZodType<
  DeleteStreamRequest$Outbound,
  z.ZodTypeDef,
  DeleteStreamRequest
> = z.object({
  stream: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteStreamRequest$ {
  /** @deprecated use `DeleteStreamRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteStreamRequest$inboundSchema;
  /** @deprecated use `DeleteStreamRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteStreamRequest$outboundSchema;
  /** @deprecated use `DeleteStreamRequest$Outbound` instead. */
  export type Outbound = DeleteStreamRequest$Outbound;
}

export function deleteStreamRequestToJSON(
  deleteStreamRequest: DeleteStreamRequest,
): string {
  return JSON.stringify(
    DeleteStreamRequest$outboundSchema.parse(deleteStreamRequest),
  );
}

export function deleteStreamRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStreamRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStreamRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStreamRequest' from JSON`,
  );
}
