/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetStreamConfigServerList = [
  "https://aws.s2.dev/v1alpha",
  /**
   * Directly access the basin
   */
  "https://{basin}.b.aws.s2.dev/v1alpha",
] as const;

export type GetStreamConfigRequest = {
  /**
   * Name of the stream.
   */
  stream: string;
  /**
   * Name of the basin. Use when accessing the basin through the Account Endpoint.
   */
  s2Basin?: string | undefined;
};

/** @internal */
export const GetStreamConfigRequest$inboundSchema: z.ZodType<
  GetStreamConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  stream: z.string(),
  "s2-basin": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "s2-basin": "s2Basin",
  });
});

/** @internal */
export type GetStreamConfigRequest$Outbound = {
  stream: string;
  "s2-basin"?: string | undefined;
};

/** @internal */
export const GetStreamConfigRequest$outboundSchema: z.ZodType<
  GetStreamConfigRequest$Outbound,
  z.ZodTypeDef,
  GetStreamConfigRequest
> = z.object({
  stream: z.string(),
  s2Basin: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    s2Basin: "s2-basin",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStreamConfigRequest$ {
  /** @deprecated use `GetStreamConfigRequest$inboundSchema` instead. */
  export const inboundSchema = GetStreamConfigRequest$inboundSchema;
  /** @deprecated use `GetStreamConfigRequest$outboundSchema` instead. */
  export const outboundSchema = GetStreamConfigRequest$outboundSchema;
  /** @deprecated use `GetStreamConfigRequest$Outbound` instead. */
  export type Outbound = GetStreamConfigRequest$Outbound;
}

export function getStreamConfigRequestToJSON(
  getStreamConfigRequest: GetStreamConfigRequest,
): string {
  return JSON.stringify(
    GetStreamConfigRequest$outboundSchema.parse(getStreamConfigRequest),
  );
}

export function getStreamConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamConfigRequest' from JSON`,
  );
}
