/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const AccountMetricSet = {
  ActiveBasins: "active_basins",
  AccountOps: "account_ops",
} as const;
export type AccountMetricSet = ClosedEnum<typeof AccountMetricSet>;

/** @internal */
export const AccountMetricSet$inboundSchema: z.ZodNativeEnum<
  typeof AccountMetricSet
> = z.nativeEnum(AccountMetricSet);

/** @internal */
export const AccountMetricSet$outboundSchema: z.ZodNativeEnum<
  typeof AccountMetricSet
> = AccountMetricSet$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountMetricSet$ {
  /** @deprecated use `AccountMetricSet$inboundSchema` instead. */
  export const inboundSchema = AccountMetricSet$inboundSchema;
  /** @deprecated use `AccountMetricSet$outboundSchema` instead. */
  export const outboundSchema = AccountMetricSet$outboundSchema;
}
