/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const BasinMetricSet = {
  Storage: "storage",
  AppendOps: "append_ops",
  ReadOps: "read_ops",
  ReadThroughput: "read_throughput",
  AppendThroughput: "append_throughput",
  BasinOps: "basin_ops",
} as const;
export type BasinMetricSet = ClosedEnum<typeof BasinMetricSet>;

/** @internal */
export const BasinMetricSet$inboundSchema: z.ZodNativeEnum<
  typeof BasinMetricSet
> = z.nativeEnum(BasinMetricSet);

/** @internal */
export const BasinMetricSet$outboundSchema: z.ZodNativeEnum<
  typeof BasinMetricSet
> = BasinMetricSet$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BasinMetricSet$ {
  /** @deprecated use `BasinMetricSet$inboundSchema` instead. */
  export const inboundSchema = BasinMetricSet$inboundSchema;
  /** @deprecated use `BasinMetricSet$outboundSchema` instead. */
  export const outboundSchema = BasinMetricSet$outboundSchema;
}
