/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Basin scope.
 */
export const BasinScope = {
  Unspecified: "unspecified",
  AwsUsEast1: "aws:us-east-1",
} as const;
/**
 * Basin scope.
 */
export type BasinScope = ClosedEnum<typeof BasinScope>;

/** @internal */
export const BasinScope$inboundSchema: z.ZodNativeEnum<typeof BasinScope> = z
  .nativeEnum(BasinScope);

/** @internal */
export const BasinScope$outboundSchema: z.ZodNativeEnum<typeof BasinScope> =
  BasinScope$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BasinScope$ {
  /** @deprecated use `BasinScope$inboundSchema` instead. */
  export const inboundSchema = BasinScope$inboundSchema;
  /** @deprecated use `BasinScope$outboundSchema` instead. */
  export const outboundSchema = BasinScope$outboundSchema;
}
