/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  StreamPosition,
  StreamPosition$inboundSchema,
  StreamPosition$Outbound,
  StreamPosition$outboundSchema,
} from "./streamposition.js";

export type CheckTailResponse = {
  /**
   * Position of a record in a stream.
   */
  tail: StreamPosition;
};

/** @internal */
export const CheckTailResponse$inboundSchema: z.ZodType<
  CheckTailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tail: StreamPosition$inboundSchema,
});

/** @internal */
export type CheckTailResponse$Outbound = {
  tail: StreamPosition$Outbound;
};

/** @internal */
export const CheckTailResponse$outboundSchema: z.ZodType<
  CheckTailResponse$Outbound,
  z.ZodTypeDef,
  CheckTailResponse
> = z.object({
  tail: StreamPosition$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckTailResponse$ {
  /** @deprecated use `CheckTailResponse$inboundSchema` instead. */
  export const inboundSchema = CheckTailResponse$inboundSchema;
  /** @deprecated use `CheckTailResponse$outboundSchema` instead. */
  export const outboundSchema = CheckTailResponse$outboundSchema;
  /** @deprecated use `CheckTailResponse$Outbound` instead. */
  export type Outbound = CheckTailResponse$Outbound;
}

export function checkTailResponseToJSON(
  checkTailResponse: CheckTailResponse,
): string {
  return JSON.stringify(
    CheckTailResponse$outboundSchema.parse(checkTailResponse),
  );
}

export function checkTailResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckTailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckTailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckTailResponse' from JSON`,
  );
}
