/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const FormatOption = {
  Json: "json",
  JsonBinsafe: "json-binsafe",
} as const;
export type FormatOption = ClosedEnum<typeof FormatOption>;

/** @internal */
export const FormatOption$inboundSchema: z.ZodNativeEnum<typeof FormatOption> =
  z.nativeEnum(FormatOption);

/** @internal */
export const FormatOption$outboundSchema: z.ZodNativeEnum<typeof FormatOption> =
  FormatOption$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FormatOption$ {
  /** @deprecated use `FormatOption$inboundSchema` instead. */
  export const inboundSchema = FormatOption$inboundSchema;
  /** @deprecated use `FormatOption$outboundSchema` instead. */
  export const outboundSchema = FormatOption$outboundSchema;
}
