/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessTokenInfo,
  AccessTokenInfo$inboundSchema,
  AccessTokenInfo$Outbound,
  AccessTokenInfo$outboundSchema,
} from "./accesstokeninfo.js";

export type ListAccessTokensResponse = {
  /**
   * If set, indicates there are more results that can be listed with `start_after`.
   */
  hasMore: boolean;
  /**
   * Access tokens information.
   */
  tokens: Array<AccessTokenInfo>;
};

/** @internal */
export const ListAccessTokensResponse$inboundSchema: z.ZodType<
  ListAccessTokensResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  has_more: z.boolean(),
  tokens: z.array(AccessTokenInfo$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});

/** @internal */
export type ListAccessTokensResponse$Outbound = {
  has_more: boolean;
  tokens: Array<AccessTokenInfo$Outbound>;
};

/** @internal */
export const ListAccessTokensResponse$outboundSchema: z.ZodType<
  ListAccessTokensResponse$Outbound,
  z.ZodTypeDef,
  ListAccessTokensResponse
> = z.object({
  hasMore: z.boolean(),
  tokens: z.array(AccessTokenInfo$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAccessTokensResponse$ {
  /** @deprecated use `ListAccessTokensResponse$inboundSchema` instead. */
  export const inboundSchema = ListAccessTokensResponse$inboundSchema;
  /** @deprecated use `ListAccessTokensResponse$outboundSchema` instead. */
  export const outboundSchema = ListAccessTokensResponse$outboundSchema;
  /** @deprecated use `ListAccessTokensResponse$Outbound` instead. */
  export type Outbound = ListAccessTokensResponse$Outbound;
}

export function listAccessTokensResponseToJSON(
  listAccessTokensResponse: ListAccessTokensResponse,
): string {
  return JSON.stringify(
    ListAccessTokensResponse$outboundSchema.parse(listAccessTokensResponse),
  );
}

export function listAccessTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAccessTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAccessTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAccessTokensResponse' from JSON`,
  );
}
