/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MetricUnit = {
  Bytes: "bytes",
  Operations: "operations",
} as const;
export type MetricUnit = ClosedEnum<typeof MetricUnit>;

/** @internal */
export const MetricUnit$inboundSchema: z.ZodNativeEnum<typeof MetricUnit> = z
  .nativeEnum(MetricUnit);

/** @internal */
export const MetricUnit$outboundSchema: z.ZodNativeEnum<typeof MetricUnit> =
  MetricUnit$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricUnit$ {
  /** @deprecated use `MetricUnit$inboundSchema` instead. */
  export const inboundSchema = MetricUnit$inboundSchema;
  /** @deprecated use `MetricUnit$outboundSchema` instead. */
  export const outboundSchema = MetricUnit$outboundSchema;
}
