/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ReadBatch,
  ReadBatch$inboundSchema,
  ReadBatch$Outbound,
  ReadBatch$outboundSchema,
} from "./readbatch.js";

export type Ping = {
  data: string;
  event: string;
};

export type ErrorT = {
  data: string;
  event: string;
};

export type Batch = {
  data: ReadBatch;
  event: string;
};

export type ReadEvent = Batch | ErrorT | Ping;

/** @internal */
export const Ping$inboundSchema: z.ZodType<Ping, z.ZodTypeDef, unknown> = z
  .object({
    data: z.string(),
    event: z.string(),
  });

/** @internal */
export type Ping$Outbound = {
  data: string;
  event: string;
};

/** @internal */
export const Ping$outboundSchema: z.ZodType<Ping$Outbound, z.ZodTypeDef, Ping> =
  z.object({
    data: z.string(),
    event: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ping$ {
  /** @deprecated use `Ping$inboundSchema` instead. */
  export const inboundSchema = Ping$inboundSchema;
  /** @deprecated use `Ping$outboundSchema` instead. */
  export const outboundSchema = Ping$outboundSchema;
  /** @deprecated use `Ping$Outbound` instead. */
  export type Outbound = Ping$Outbound;
}

export function pingToJSON(ping: Ping): string {
  return JSON.stringify(Ping$outboundSchema.parse(ping));
}

export function pingFromJSON(
  jsonString: string,
): SafeParseResult<Ping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ping' from JSON`,
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    data: z.string(),
    event: z.string(),
  });

/** @internal */
export type ErrorT$Outbound = {
  data: string;
  event: string;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  data: z.string(),
  event: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorT$ {
  /** @deprecated use `ErrorT$inboundSchema` instead. */
  export const inboundSchema = ErrorT$inboundSchema;
  /** @deprecated use `ErrorT$outboundSchema` instead. */
  export const outboundSchema = ErrorT$outboundSchema;
  /** @deprecated use `ErrorT$Outbound` instead. */
  export type Outbound = ErrorT$Outbound;
}

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const Batch$inboundSchema: z.ZodType<Batch, z.ZodTypeDef, unknown> = z
  .object({
    data: z.string().transform((v, ctx) => {
      try {
        return JSON.parse(v);
      } catch (err) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `malformed json: ${err}`,
        });
        return z.NEVER;
      }
    }).pipe(ReadBatch$inboundSchema),
    event: z.string(),
  });

/** @internal */
export type Batch$Outbound = {
  data: ReadBatch$Outbound;
  event: string;
};

/** @internal */
export const Batch$outboundSchema: z.ZodType<
  Batch$Outbound,
  z.ZodTypeDef,
  Batch
> = z.object({
  data: ReadBatch$outboundSchema,
  event: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Batch$ {
  /** @deprecated use `Batch$inboundSchema` instead. */
  export const inboundSchema = Batch$inboundSchema;
  /** @deprecated use `Batch$outboundSchema` instead. */
  export const outboundSchema = Batch$outboundSchema;
  /** @deprecated use `Batch$Outbound` instead. */
  export type Outbound = Batch$Outbound;
}

export function batchToJSON(batch: Batch): string {
  return JSON.stringify(Batch$outboundSchema.parse(batch));
}

export function batchFromJSON(
  jsonString: string,
): SafeParseResult<Batch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Batch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Batch' from JSON`,
  );
}

/** @internal */
export const ReadEvent$inboundSchema: z.ZodType<
  ReadEvent,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => Batch$inboundSchema),
  z.lazy(() => ErrorT$inboundSchema),
  z.lazy(() => Ping$inboundSchema),
]);

/** @internal */
export type ReadEvent$Outbound =
  | Batch$Outbound
  | ErrorT$Outbound
  | Ping$Outbound;

/** @internal */
export const ReadEvent$outboundSchema: z.ZodType<
  ReadEvent$Outbound,
  z.ZodTypeDef,
  ReadEvent
> = z.union([
  z.lazy(() => Batch$outboundSchema),
  z.lazy(() => ErrorT$outboundSchema),
  z.lazy(() => Ping$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadEvent$ {
  /** @deprecated use `ReadEvent$inboundSchema` instead. */
  export const inboundSchema = ReadEvent$inboundSchema;
  /** @deprecated use `ReadEvent$outboundSchema` instead. */
  export const outboundSchema = ReadEvent$outboundSchema;
  /** @deprecated use `ReadEvent$Outbound` instead. */
  export type Outbound = ReadEvent$Outbound;
}

export function readEventToJSON(readEvent: ReadEvent): string {
  return JSON.stringify(ReadEvent$outboundSchema.parse(readEvent));
}

export function readEventFromJSON(
  jsonString: string,
): SafeParseResult<ReadEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadEvent' from JSON`,
  );
}
