/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Age in seconds for automatic trimming of records older than this threshold.
 *
 * @remarks
 * If set to 0, the stream will have infinite retention.
 */
export type Age = {
  /**
   * Age in seconds for automatic trimming of records older than this threshold.
   *
   * @remarks
   * If set to 0, the stream will have infinite retention.
   */
  age: number;
};

/**
 * Retention policy for the stream.
 *
 * @remarks
 * If unspecified, the default is to retain records for 7 days.
 */
export type RetentionPolicy = Age;

/** @internal */
export const Age$inboundSchema: z.ZodType<Age, z.ZodTypeDef, unknown> = z
  .object({
    age: z.number().int(),
  });

/** @internal */
export type Age$Outbound = {
  age: number;
};

/** @internal */
export const Age$outboundSchema: z.ZodType<Age$Outbound, z.ZodTypeDef, Age> = z
  .object({
    age: z.number().int(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Age$ {
  /** @deprecated use `Age$inboundSchema` instead. */
  export const inboundSchema = Age$inboundSchema;
  /** @deprecated use `Age$outboundSchema` instead. */
  export const outboundSchema = Age$outboundSchema;
  /** @deprecated use `Age$Outbound` instead. */
  export type Outbound = Age$Outbound;
}

export function ageToJSON(age: Age): string {
  return JSON.stringify(Age$outboundSchema.parse(age));
}

export function ageFromJSON(
  jsonString: string,
): SafeParseResult<Age, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Age$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Age' from JSON`,
  );
}

/** @internal */
export const RetentionPolicy$inboundSchema: z.ZodType<
  RetentionPolicy,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => Age$inboundSchema);

/** @internal */
export type RetentionPolicy$Outbound = Age$Outbound;

/** @internal */
export const RetentionPolicy$outboundSchema: z.ZodType<
  RetentionPolicy$Outbound,
  z.ZodTypeDef,
  RetentionPolicy
> = z.lazy(() => Age$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetentionPolicy$ {
  /** @deprecated use `RetentionPolicy$inboundSchema` instead. */
  export const inboundSchema = RetentionPolicy$inboundSchema;
  /** @deprecated use `RetentionPolicy$outboundSchema` instead. */
  export const outboundSchema = RetentionPolicy$outboundSchema;
  /** @deprecated use `RetentionPolicy$Outbound` instead. */
  export type Outbound = RetentionPolicy$Outbound;
}

export function retentionPolicyToJSON(
  retentionPolicy: RetentionPolicy,
): string {
  return JSON.stringify(RetentionPolicy$outboundSchema.parse(retentionPolicy));
}

export function retentionPolicyFromJSON(
  jsonString: string,
): SafeParseResult<RetentionPolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RetentionPolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RetentionPolicy' from JSON`,
  );
}
