/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const S2Format = {
  Raw: "raw",
  Base64: "base64",
} as const;
export type S2Format = ClosedEnum<typeof S2Format>;

/** @internal */
export const S2Format$inboundSchema: z.ZodNativeEnum<typeof S2Format> = z
  .nativeEnum(S2Format);

/** @internal */
export const S2Format$outboundSchema: z.ZodNativeEnum<typeof S2Format> =
  S2Format$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace S2Format$ {
  /** @deprecated use `S2Format$inboundSchema` instead. */
  export const inboundSchema = S2Format$inboundSchema;
  /** @deprecated use `S2Format$outboundSchema` instead. */
  export const outboundSchema = S2Format$outboundSchema;
}
