/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const StorageClass = {
  Standard: "standard",
  Express: "express",
} as const;
export type StorageClass = ClosedEnum<typeof StorageClass>;

/** @internal */
export const StorageClass$inboundSchema: z.ZodNativeEnum<typeof StorageClass> =
  z.nativeEnum(StorageClass);

/** @internal */
export const StorageClass$outboundSchema: z.ZodNativeEnum<typeof StorageClass> =
  StorageClass$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StorageClass$ {
  /** @deprecated use `StorageClass$inboundSchema` instead. */
  export const inboundSchema = StorageClass$inboundSchema;
  /** @deprecated use `StorageClass$outboundSchema` instead. */
  export const outboundSchema = StorageClass$outboundSchema;
}
