/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  StreamPosition,
  StreamPosition$inboundSchema,
  StreamPosition$Outbound,
  StreamPosition$outboundSchema,
} from "./streamposition.js";

export type TailResponse = {
  /**
   * Position of a record in a stream.
   */
  tail: StreamPosition;
};

/** @internal */
export const TailResponse$inboundSchema: z.ZodType<
  TailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tail: StreamPosition$inboundSchema,
});

/** @internal */
export type TailResponse$Outbound = {
  tail: StreamPosition$Outbound;
};

/** @internal */
export const TailResponse$outboundSchema: z.ZodType<
  TailResponse$Outbound,
  z.ZodTypeDef,
  TailResponse
> = z.object({
  tail: StreamPosition$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TailResponse$ {
  /** @deprecated use `TailResponse$inboundSchema` instead. */
  export const inboundSchema = TailResponse$inboundSchema;
  /** @deprecated use `TailResponse$outboundSchema` instead. */
  export const outboundSchema = TailResponse$outboundSchema;
  /** @deprecated use `TailResponse$Outbound` instead. */
  export type Outbound = TailResponse$Outbound;
}

export function tailResponseToJSON(tailResponse: TailResponse): string {
  return JSON.stringify(TailResponse$outboundSchema.parse(tailResponse));
}

export function tailResponseFromJSON(
  jsonString: string,
): SafeParseResult<TailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TailResponse' from JSON`,
  );
}
