/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TimestampingMode,
  TimestampingMode$inboundSchema,
  TimestampingMode$outboundSchema,
} from "./timestampingmode.js";

export type TimestampingConfig = {
  mode?: TimestampingMode | null | undefined;
  /**
   * Allow client-specified timestamps to exceed the arrival time.
   *
   * @remarks
   * If this is false or not set, client timestamps will be capped at the arrival time.
   */
  uncapped?: boolean | null | undefined;
};

/** @internal */
export const TimestampingConfig$inboundSchema: z.ZodType<
  TimestampingConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: z.nullable(TimestampingMode$inboundSchema).optional(),
  uncapped: z.nullable(z.boolean()).optional(),
});

/** @internal */
export type TimestampingConfig$Outbound = {
  mode?: string | null | undefined;
  uncapped?: boolean | null | undefined;
};

/** @internal */
export const TimestampingConfig$outboundSchema: z.ZodType<
  TimestampingConfig$Outbound,
  z.ZodTypeDef,
  TimestampingConfig
> = z.object({
  mode: z.nullable(TimestampingMode$outboundSchema).optional(),
  uncapped: z.nullable(z.boolean()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TimestampingConfig$ {
  /** @deprecated use `TimestampingConfig$inboundSchema` instead. */
  export const inboundSchema = TimestampingConfig$inboundSchema;
  /** @deprecated use `TimestampingConfig$outboundSchema` instead. */
  export const outboundSchema = TimestampingConfig$outboundSchema;
  /** @deprecated use `TimestampingConfig$Outbound` instead. */
  export type Outbound = TimestampingConfig$Outbound;
}

export function timestampingConfigToJSON(
  timestampingConfig: TimestampingConfig,
): string {
  return JSON.stringify(
    TimestampingConfig$outboundSchema.parse(timestampingConfig),
  );
}

export function timestampingConfigFromJSON(
  jsonString: string,
): SafeParseResult<TimestampingConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimestampingConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimestampingConfig' from JSON`,
  );
}
