/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TimestampingMode = {
  ClientPrefer: "client-prefer",
  ClientRequire: "client-require",
  Arrival: "arrival",
} as const;
export type TimestampingMode = ClosedEnum<typeof TimestampingMode>;

/** @internal */
export const TimestampingMode$inboundSchema: z.ZodNativeEnum<
  typeof TimestampingMode
> = z.nativeEnum(TimestampingMode);

/** @internal */
export const TimestampingMode$outboundSchema: z.ZodNativeEnum<
  typeof TimestampingMode
> = TimestampingMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TimestampingMode$ {
  /** @deprecated use `TimestampingMode$inboundSchema` instead. */
  export const inboundSchema = TimestampingMode$inboundSchema;
  /** @deprecated use `TimestampingMode$outboundSchema` instead. */
  export const outboundSchema = TimestampingMode$outboundSchema;
}
