/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TimeseriesInterval = {
  Minute: "minute",
  Hour: "hour",
  Day: "day",
} as const;
export type TimeseriesInterval = ClosedEnum<typeof TimeseriesInterval>;

/** @internal */
export const TimeseriesInterval$inboundSchema: z.ZodNativeEnum<
  typeof TimeseriesInterval
> = z.nativeEnum(TimeseriesInterval);

/** @internal */
export const TimeseriesInterval$outboundSchema: z.ZodNativeEnum<
  typeof TimeseriesInterval
> = TimeseriesInterval$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TimeseriesInterval$ {
  /** @deprecated use `TimeseriesInterval$inboundSchema` instead. */
  export const inboundSchema = TimeseriesInterval$inboundSchema;
  /** @deprecated use `TimeseriesInterval$outboundSchema` instead. */
  export const outboundSchema = TimeseriesInterval$outboundSchema;
}
